### ISSUE TITLE
按钮的一个样式，鼠标滑上去有个闪光的效果

### ISSUE THREAD

**Issue by Go7hic** [dyygtfx/EveryDayCode#36]
``` html
<a id="show-more">More</a>
```

``` css
#show-more {
display: block;
width: 200px;
height: 60px;
margin: 0 auto;
background: #57ad68;
font-size: 24px;
line-height: 60px;
text-align: center;
border-radius: 30px;
color: white;
text-shadow: 0 1px 0 #57ad68;
cursor: pointer;
position: relative;
overflow: hidden;
margin-top: 50px;
-webkit-user-select: none;
-moz-user-select: none;
-mz-user-select: none;
user-select: none;
}
#show-more:hover:before {
transform: scale(1, 1);
-webkit-transform: scale(1, 1);
}
#show-more:before {
content: ' ';
display: block;
background: rgba(255, 255, 255, .2);
position: absolute;
left: 0;
top: 0;
right: 0;
bottom: 0;
border-radius: 30px;
transform: scale(0, 1);
-webkit-transform: scale(0, 1);
transition: transform 0.3s ease;
-webkit-transition: -webkit-transform 0.3s ease;
}
```

demo : http://jsfiddle.net/gothic/zk4jbnqn/1/
